function status = write_ascii_ppm(img, file_name)
% write image as an ascii ppm-file

img_size = size(img);

file_handle=fopen(file_name,"w");
fprintf(file_handle,"P12\n");
fprintf(file_handle,"# generated by Octave\n");
fprintf(file_handle,"%i %i\n",img_size(2),img_size(1));
fprintf(file_handle,"255\n");
for y = 1 : img_size(1)
  for x = 1 : img_size(2)
    fprintf(file_handle,"%i %i %i\n",img(y,x,:));
  end
end

status = fclose(file_handle);

endfunction
